.\" select.8
.\"
.\" Copyright (c) 2007 The MacPorts Project
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Apple Computer, Inc. nor the names of its
.\"    contributors may be used to endorse or promote products derived from
.\"    this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd July 26, 2007
.Dt __NAME___SELECT 8 "MacPorts"
.Os
.Sh NAME
.Nm __NAME___select
.Nd choose between multiple versions of the same or similar tool
.Sh SYNOPSIS
.Nm
.Op Fl ndfhrvls
.Op Ar version
.Op Ar -i path
.Sh DESCRIPTION
.Nm
lets you choose between multiple versions of the same or a similar software
.Pp
.Sh FILES
.Bl -tag -width
.It Va __PREFIX__/etc/select/__NAME__/base
Base configuration for the software __NAME__. Each line in the file specifies a file that __NAME___select provides by symlinking it to a target file. Paths will all be prefixed by the prefix provided at install time (__PREFIX__ in this case).
.br
.Sy Example:
.Dl bin/foo
.Dl sbin/bar
.Dl share/man/man1/foo.1.gz
.br
.It Va __PREFIX__/etc/select/__NAME__/${version}
Configuration for a specific version of the software __NAME__. This provides one possibility to choose from. When this version is selected, all files from the base configuration get symlinked to the corresponding files in the version file. Each line in the base configuration file corresponds to the same line in the version file. If the version cannot provide a target file, the line in the version file has to start with a '-' (The symlink will then be deleted if this version is activated). Lines may start with a '/' for absolut an absolut path. If lines do not start with a '/', they will be prefixed by __PREFIX__.
.br
.Sy Example:
.Dl bin/foo-5.9
.Dl /sbin/false
.Dl -
.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr gcc_select 8
.Sh AUTHOR
.An "Markus W. Weissmann" Aq mww@macports.org
